[package]
name = "pqcrypto-std"
version = "0.1.0"
edition = "2021"
authors = ["Jørgen Kristensen <jk@bitnor.org>"]

[dependencies]
rand_core = { version = "0.6.4", default-features = false }
sha3 = { version = "0.10.8", default-features = false }
zeroize = { version = "1.8.1", default-features = false }

[dev-dependencies]
hex = { version = "0.4.3", features = ["serde"] }
rand = { version = "0.8.5" }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128" }
